- app/Randomizer.php
Ruble suggested "Salamander" and it does in fact fit the 10-character requirement.
> More Saha names

- app/Randomizer.php
Kliff mentioned "Sassafrass" and I noticed that it's not in the code as an option. This will add it.
> Add a Saha name

- resources/views/help.blade.php
- resources/views/randomizer.blade.php
> Fix max item count custom difficulty, help page text

- app/World.php
Fixes #182 
I tested generating 100 seeds with the previous code with PoD key added to the list and this version with the key check removed (so they are all processed) and the generation speed is faster with this version.
> fix spoiler step skipping/truncating

- routes/web.php
New pull request to accommodate the requested format
> Added route to get information about the base rom patch

- resources/views/about.blade.php
minor updates to the home page copy
> home page updates

- app/EntranceRandomizer.php
- composer.json
- composer.lock
- config/alttp.php
The main changes relevant for the VT site are:
* OHKO mode implemented
* fixed a POD softlock
> Update to Entrance Randomizer v0.5.1

- app/Rom.php
- app/Support/Dialog.php
Hi, I just saw a couple things in here that could use a little bit of cleanup so I thought I'd open a PR. All the tests pass. Love the randomizer races, thanks for all your hard work!
> Dialog refactoring

- app/Rom.php
- resources/assets/js/rom.js
This should fix the checksum calculation.
> Fix checksum calculation

- app/EntranceRandomizer.php
- composer.json
- composer.lock
Fixes softlocks caused by broken bunny logic.
> Pull in ER softlock fix

- resources/views/resources.blade.php
> Fix typo in resources.blade.php

- resources/views/resources.blade.php
- resources/views/start.blade.php
See #398. These changes should be good to merge without further discussion.
> Some pitfall clarifications 2

- readme.md
As discussed in #402, here's a small restructuring of the readme to separate CLI/web stuff a bit better.
I also took the opportunity to clarify that bug reports off development branches are not welcome.
> Restructure readme and add bug report information

- app/EntranceRandomizer.php
- composer.json
- composer.lock
- config/alttp.php
Update to the newly released Entrance Randomizer 0.6.0
> Update to Entrance Randomizer 0.6.0

- app/EntranceRandomizer.php
- composer.json
- composer.lock
- config/alttp.php
- resources/views/_rom_spoiler.blade.php
- routes/web.php
> Update to ER 0.6.1

- app/Location/Drop/Bombos.php
- app/Location/Drop/Ether.php
- app/Location/Pedestal.php
> [spelling] Agahnim spelling fix. Fixes #488

- app/Randomizer.php
Please use any or all of these new Blind puns.  They should all fit the allotted space and the overall cadence of Blind puns, and I hope most or all all are appropriate for inclusion.  When hundreds of seeds are broadcast, more pun variety is good!
> Nine new Blind pun suggestions

- strings/blind.txt
> A tenth pun suggestion

- strings/ganon_1.txt
Keep what you like, cut what you don't.
> Some Ganon quotes

- app/Randomizer.php
If we can reference songs, we can reference Sailor Moon.
> Wishing Well credit line suggestions

- strings/blind.txt
Just thought of this one today.
> Another Blind pun suggestion

- app/Randomizer.php
> Two more Sahasralah names

- strings/blind.txt
I can't take full credit for this one.  AmazingAmpharos claimed he'd lose viewers for a similar pun.
> Yet another Blind pun

- app/Helpers/number.php
- app/Rom.php
- app/Text.php
- resources/assets/js/components/VTRomInfo.vue
- resources/assets/js/rom.js
- tests/HelpersTest.php
> Minor updates

- strings/hint.txt
Though plogues (pronounced "ployes") ARE easy to make and yummy.
> Two more joke hints

- strings/fortune.txt
Since we seem to be putting common pitfalls here...
> New fortunes

- strings/blind.txt
Hanging around other punsters got me thinking again.
> More puns!

- resources/views/options.blade.php
This fixes the website Difficulty Comparison for mail in pool for Hard
mode.
This fixes issue #599
> Fix website documentation of hard mode mail count

- strings/triforce.txt
Hey, Synack here.  This specifically refers to the DC metro saying "This is a 7000-series train." on every stop while we were at AGDQ 2019.  Figured it would be amusing (you can reject it if you don't think its appropriate).
> A meme from AGDQ 2019 for the Triforce Room.

- app/Region/Inverted/DarkWorld/DeathMountain/East.php
Allows for the ability to mirror to EDWDM if you dont have byrna/cape and cant take damage.
> EDWDM Inverted Access fix

- readme.md
Ran into this issue on first time setup, adding to readme to prevent future people from hitting this.
> Need laravel-vue include file to run npm production

- strings/blind.txt
- strings/ganon_1.txt
- strings/triforce.txt
Here are some of the better Blind, Ganon, and Triforce strings suggested by our community.  I'd like to propose them as additions to the main branch.
> Community-sourced Blind, Ganon, and Triforce strings from the Spoiler Tournament

- app/Randomizer.php
What always gets said to priestly characters...
> An ending string

- strings/hint.txt
Going with the obvious in-joke here.  ;)
> One more joke hint

- app/Console/Commands/Randomize.php
> Remove typo in Randomize.php

- app/World.php
Don't overflow silvers for swordless seeds.
> Fix silvers becoming rupees on hard/swordless

- app/Region/Inverted/LightWorld/South.php
- app/Region/Standard/DarkWorld/DeathMountain/West.php
- app/Region/Standard/GanonsTower.php
- app/Region/Standard/LightWorld/DeathMountain/East.php
Typo in Standard EDM Logic
Remove Sword from Spinspeed Entry to GT 
-only need Hookshot, while Sword won't make this clip possible on it's own
> Fixing a bunch of small stuff

- strings/blind.txt
- strings/ganon_1.txt
- strings/hint.txt
- strings/uncle.txt
These suggestions for Uncle, Blind, and Hints came from the Go Mode Podcast community.  Thanks for reviewing.
> Text suggestions from the community.

- app/Filler/RandomAssumed.php
- app/Support/WorldCollection.php
- app/World.php
#772 
CollectOtherItems is called in a loop, so need to make sure it doesn't recollect the same items.
> Fix pre_collected_items being collected multiple times

- app/Randomizer.php
Beatable only logic with the superquick preset requires the tempered sword to function.
> Fix basic beatable only logic

- strings/blind.txt
Because it came up in Twitch chat!
> A community pun

- strings/blind.txt
> Another pun

- app/Text.php
Updated stuff that's cut, too, just in case.
A little punctuation tweaking too, though you'll have to evaluate whether any of those will break anything.
> Capitalization in Text.php

- strings/uncle.txt
Didn't touch "I AM ERROR", though.
> Uncle string capitalization update

- strings/triforce.txt
Because in addition to the capitalization assignment, I've noticed Triforce strings wrapping wrong these days.  See if these tweaks help.
> Triforce capitalization and attempted string wrap fixes

- app/EntranceRandomizer.php
- app/Rom.php
- app/World.php
- composer.json
- resources/js/app.js
- resources/views/layouts/default.blade.php
- resources/views/updates.blade.php
- routes/console.php
Update website to use ER 0.6.3-pre9
Use the new --securerandom flag when generating ER games
Comment out the Twitch streams, as the Twitch API is broken and is just causing console errors
Set the tournament flag on dailies
Add release notes
> Several updates for v31.0.6

- strings/triforce.txt
Because I overheard this proposal in an SMZ3 commentary.
> Triforce line

- app/Randomizer.php
Because I heard this in the Crosskeys grand finals.
> Another Sahasralah name

- strings/blind.txt
> A couple more puns

- strings/ganon_1.txt
Suggesting adding David Bowie's "Magic Dance" and Gloria Gaynor's "I Will Survive" as possible Ganon text
> Add alternative lines

- strings/blind.txt
feel free to toss any or all of them out if they don't make you laugh
> just some dumb and silly puns i thought of

- strings/blind.txt
> Yet another pun

- app/Console/Commands/Randomize.php
- app/Rom.php
- resources/js/components/VTRomSettings.vue
- resources/js/rom.js
- resources/js/store/modules/romSettings.js
- resources/js/vue-i18n-locales.generated.js
- resources/lang/de/rom.php
- resources/lang/en/rom.php
- resources/lang/es/rom.php
- resources/lang/fr/rom.php
- tests/RomTest.php
- Adds 'Random' as a 5th option to the "Heart Color" selector
- Implements the randomization for the CLI PHP ROM generation and JS ROM generation
- Added language translations for the word "Random" for English, Spanish, French, and German
- Asked friends who speak said languages natively to source these translations
- Tests Added (for PHP version)
- Refactored the assertion of color setting into a private method within the test file
- Added test to assure that the default case is handled (i.e. a nonsensical value is passed, and it defaults to `red`)
- CLI Support for heart color added
- `--heartcolor=HEARTCOLOR` (defaults to `red`)
> Random Heart Color Option + CLI Option for Heart Color

- app/Location/Npc/Uncle.php
- app/World.php
Uncle will give resources in the following way
1. If he has a weapon, he will give resources for that weapon
2. Else, if the player starts with a weapon then he will give resources for the starting weapon(s), looking for weapons that require nothing, magic, arrows, bombs in that order.
3. Else, if the game is not no-logic then he will give bombs so the player has a way to finish escape (this can happen if he was plandod to not have a weapon).
Note: For the purposes of enemy health shuffle, Ten Bombs and the Cane of Byrna do not count as weapons.
>  Set escape resources based on starting equipment if Uncle doesn't have a weapon.

- strings/ganon_phase_3_no_silvers.txt
Since we're doing these now, here's a few!
> Silver arrow texts

- strings/blind.txt
Glad I could make this one fit!
> Community pun

- strings/hint.txt
Because it occurred to me that a useless fact like this might work for this purpose.
> New joke hint

- strings/credits.yml
I have added blacksmith strings for everything, preserving "The Breadsmiths" in health upgrades.  I've also replaced various "nothing" string sets with either new ones or near matches, though the nothing strings remain for actual null results.
> Dwarves and more!

- strings/ganon_1.txt
Tweaking one of my old submissions, adding a new one in the useless facts tradition, tweaking some capitalizations in other submissions, etc.  If ampersands don't work for my own new submission, try "DnD" and "ADnD" instead.
> 17-character update

- strings/blind.txt
Let's make fun of famous runners!
> Not out of puns yet!

- strings/uncle.txt
> Another "only one bed" Uncle joke

- strings/blind.txt
Well, more "perfect addition I tripped over and asked permission to use", but still.
> Community submission

- strings/blind.txt
Now if only I had more ideas for Ganon quotes instead...
> The puns keep coming

- app/Rom.php
- composer.json
- composer.lock
- package-lock.json
- resources/js/rom.js
Depends on merging https://github.com/KatDevsGames/z3randomizer/pull/198, composer.json/lock are based on refs from the original branch of that.
> Fix permalink heart color patching

- app/Rom.php
- composer.json
- composer.lock
Depends on merging of https://github.com/KatDevsGames/z3randomizer/pull/199, lock file is based on build from original branch
> V31.2.0 glitch ROM fixes

- resources/lang/en/races.php
Just fix a small typo in the races.php file.
> Fix typo in races.php file.
