sporchia/alttp_vt_randomizer

resources/views/randomizer.blade.php
Remove empty &lt;div&gt; on Custom Options page that was causing some odd layout behavior.
=> Remove empty div on Custom Options page

resources/views/entrance_randomizer.blade.php
Removes Standard as a Mode option from the Entrance Randomizer front-end
=> Remove Standard from Entrance Randomizer

app/EntranceRandomizer.php, composer.json, composer.lock, config/alttp.php, resources/views/_rom_spoiler.blade.php
Update to use version 0.5.0 of the Entrance Randomizer.
I've also copied in the latest blind/uncle/triforce etc messages from the item randomizer. Eventually that code should be removed, since ER should incorporate a sufficiently large set of them for each area, but that has not happened yet.
I've kept the options mirroring what Item Randomizer offers. I do know that AmazingAmpharos would prefer to restructure the web version to offer additional options. For example ER the timer modes are independent of the Triforce Hunt goal, and both are independent of key-sanity.
Similarly, apparently many ER racers don't like the web version because it does not offer the shuffle-ganon option in simple and full shuffle modes. 
I could add additional options for these if you want them, but thought …
=> Entrance update

app/Region/GanonsTower.php
I found something in the ganon's tower code that is almost definitely a typo.
Fixing this typo _will_ slightly change seed generation; it means that ganon's tower will sometimes require fewer small keys to complete according to the logic.
I don't understand exactly why the location of the big key should affect how many small keys you need, so someone should double-check this logic and make sure this typo fix isn't introducing a softlock.
=> fix typo in ganon's tower big key logic

app/EntranceRandomizer.php, composer.json, composer.lock, resources/assets/sass/app.scss, resources/views/_rom_spoiler.blade.php
This pull request is for integrating the soon to be released Entrance Randomizer version 0.5.2.
As for what is new that is applicable to the site:
It adds the applicable logic updates from v28.
It has bunny logic now (in theory you can be required to do things like get the hype cave item as a bunny, although this very rarely happens).
It now has updated messages (largely borrowed from this site), so the code to overwrite the messages in php has been removed. 
It also adds a new paths section to the spoiler log, which lists how to get to each area mentioned in the playthrough. The `_rom_spoiler.blade.php` file has been updated to accommodate this, and display it cleanly.
Fixes #338
=> Upgrade to support ER v0.5.2 

app/Rom.php, resources/assets/js/rom.js
Apparently I had some weird cache issues on my dev box when I was testing, which was causing my generated checksums to come out right even though the code was actually wrong.  @KevinCathcart had it right in the Entrance Rando, so I'm correcting the VT rando checksum code to match his.  The addition of the 0x1FE is due to the official documentation specifying that the header checksum field should be set to 0xFFFF and the complement to 0x0000 when calculating the checksum, which is the same as skipping both fields *and adding 0xFF + 0xFF* which is what I was missing.
=> Fixed checksums (for real this time)

resources/views/_rom_settings.blade.php
With the update to css bolding h4 tags, this looks out of place, and I suspect it should've been h3 anyway.
Other panel-title headers throughout the site are all h3 and look great without the bolding.  This one looks great without the bold (v28/master), but the css bold for h4 (v29) ends up applied to it and doesn't look right compared to the rest of the site and the nearby h3 panel-title.
=> Rom options header h4 to h3

app/Text.php
This replaces `taht` with `that`.
=> Fix spelling of the handy's message.

app/Console/Commands/Randomize.php, app/Console/Commands/UpdateBaseJson.php
This fixes the command line generation file names to match the website, since Karkat finds the difference in naming convention confusing.
I also updated the `updatebase` command to accept a 1MB vanilla rom instead of requiring a 2MB vanilla rom.
=> Command Line Fixes

app/Console/Commands/MakeTranslation.php, app/Enemizer.php, app/Randomizer.php, app/Rom.php, app/Text.php
Return text to the text table to match recently merged changes in the Base ROM.
The list of strings to blank out were kept separate so as not to discard the actual translations of the relevant lines. This makes it easy to remove or restore individual dialog lines on demand.
=> Move text back into Text Table

app/Region/Inverted/TurtleRock.php
The bug causes upper TRock entrance to think you need LW access to get to it.
=> Top Entrance Requirement Bug

app/Support/ItemCollection.php
Fix issue #615: the active flute should be available immediately without having to activate it in the light world.
=> Always allow flying in inverted mode with the active flute.

app/Location/Drop/Ether.php
On the topic of the descriptions:
The descriptions for Ether and Bombos are identical, Pedestal differs only in one description. Having triple instances of text that is supposed to stay the same seems like a good way to introduce errors. Wouldn't it be a good idea to collect the descriptions for tablets and pedestal in some common base?
One could have a standalone function with all default descriptions (say, based on Bombos/Ether) and then let Bombos/Ether just call that function while Pedestal special cases sword upgrades before calling the function.
=> Typo in Ether tablet item description

app/Region/Standard/SkullWoods.php
Found a leftover check that prevents progression items from being placed in this room.
=> Allow progression in Pinball Room when not forcing key.

app/Boss.php, app/Randomizer.php, app/Region/Inverted/GanonsTower.php, app/Region/Standard/PalaceOfDarkness.php, app/Services/HintService.php
Account for GT required crystals in Inverted mode #718 .
PoD dark maze etc to always require 6 keys in keysanity mode (since the logic can't determine if the bow/hammer is completely inaccessible).  And also add some fill rules to make sure the customizer doesn't put keys in dark maze.  #658 
Allow Pedestal Goal and Vanilla Swords to be used (sword on pedestal is replaced with Triforce).
Kholdstare is not beatable with only Fire Rod, Bombos and a bottle unless this is swordless mode and Bombos can actually be used.
Fix Windows line endings when parsing the hints / text.
=> Logic Fixes

app/Randomizer.php
Same behavior as swordless since there's already four swords in the pool.
=> Change take any sword to 300 rupees when swords are vanilla

.github/ISSUE_TEMPLATE, app/Http/Controllers/CustomizerController.php, app/World.php, resources/js/store/modules/context.js, resources/js/views/Customizer.vue
Tested locally by saving and loading Customizer templates with and without these options, generating custom games with and without hints, and with and without dungeon item menu and item text boxes turned on. Also generated a few regular Randomizer seeds to test for regressions. All PHPUnit tests pass.
I kept this in two separate atomic commits, but I can squash them into one if you'd prefer.
The menu and text box fix was straightforward, but the hints bug was more complex, and I welcome feedback on my approach.
So, hints weren't working for a few reasons: 
- the hints value was not being sent in the POST request
- the hints dropdown is attached to a value called randomizer.hints, but there is a redundant value in vt.custom.settings called spoil.Hints that is not updated when the dropdown …
=> Fix Dungeon Item Menu/Text Box and Hints options in Customizer

app/Http/Controllers/CustomizerController.php, resources/js/components/Customizer/Glitches.vue, resources/js/store/modules/context.js, resources/js/store/modules/glitches.js, resources/js/vue-i18n-locales.generated.js, resources/lang/de/customizer.php, resources/lang/en/customizer.php, resources/lang/en/options.php, resources/lang/es/customizer.php, resources/lang/fr/customizer.php, resources/views/options.blade.php, resources/views/updates.blade.php
Fixes #730 - Customizer games do not have manually placed triforce pieces when verifying there are enough goal items to complete the game.
Clarifies on options page Advanced Item Placement's dark room logic, this has been a point of confusion for a while now on both Discord and in the github issues here.
Clarifies on options page how the Item Pool and Item Functionality settings affect silver arrows.  This has also been a point of confusion on both the Discord and in the github issues.
Added canOneFrameClipUW to customizer logic settings page.
Removed canBombJump and canWaterFairyRevive from the customizer logic settings page, as they're not used in the logic anywhere at this time.  I think they can always be re-added if necessary.
Added ability to set the ROM fixes applied (or not …
=> Miscellaneous Customizer and Site Copy Fixes for v31.0.3

app/Region/Inverted/DarkWorld/NorthWest.php
Adding Brackets to Fix Smith and Purple Chest Logic.
Previous logic would have put those locations in logic with very minimal items (mitts/mirror)
=> 31.0.3 invertedfixes

app/Http/Controllers/CustomizerController.php, app/Http/Controllers/RandomizerController.php, config/alttp.php, resources/js/components/VTRomInfo.vue, resources/js/vue-i18n-locales.generated.js, resources/lang/de/rom.php, resources/lang/en/rom.php, resources/lang/es/rom.php, resources/lang/fr/rom.php, routes/console.php
Adds a 5% chance that a daily challenge will be a mystery.  The game is rolled using the same weights as other dailies.
Do not filter out name and notes in the spoiler meta.
Add a message to VTRomInfo.vue informing the player that it is a mystery game.  Message is translated in FR, DE, and ES.
This is setup in a way where we could eventually have spoiler dailies, however it is not turned on at this time.  Generate is also weighted at 0 because it won't work at this time and instead just behave like spoilers were on.
=> Add a chance of a daily games being a mystery

app/Support/ItemCollection.php, app/World/Retro.php
Fixes issue #769 where retro mode required all keys.
Remove 10 keys from normal retro, and 15 from hard/expert/crowd item pools.
=> Retro Key Logic

app/Region/Inverted/DesertPalace.php, app/Region/Inverted/LightWorld/South.php, app/Region/Open/HyruleCastleEscape.php, app/Region/Standard/DesertPalace.php, app/Region/Standard/LightWorld/South.php, app/Support/ItemCollection.php
There was a Daily Recently which forced progression behind high Health Mini Moldorms in Mini Moldorm Cave before Weapons were available (or Flippers for the Upgrade Fairy).
This prevents the issue from reappearing by forcing a weapon that can kill anything before those locations that require you to kill enemies, if Enemy Health is randomized. (not caring if the enemies are set to 1 heart or 8)
=> Add check for Randomized Enemy Health

resources/js/views/HashLoader.vue
I forgot to add `|| this.rom.allow_quickswap` to the logic condition for showing the Item Quickswap option when the game is loaded from s3.
=> V31.0.5 - Fix quickswap when patch is retrieved via S3

resources/js/rom.js
This prevents the .txt extension from showing up on ROMs saved from mobile Chrome.
=> Set proper Content-Type on saved ROM

.env.example, app/Console/Commands/Distribution.php, app/Console/Commands/Randomize.php, app/Enemizer.php, app/Http/Controllers/CustomizerController.php, app/Http/Controllers/MultiworldController.php, app/Http/Controllers/RandomizerController.php, app/Http/Kernel.php, app/Http/Middleware/ThrottleRequestsWithIp.php, app/Http/Requests/CreateRandomizedGame.php, app/Rom.php, app/World.php, config/alttp.php, routes/api.php, routes/console.php
This commit adds two features.
1) Adds pot shuffle as an API-only option in both the Randomizer and Customizer endpoints.
2) Adds a configuration option that lets us set a list of IP addresses to be whitelisted.  Whitelisted addresses bypass throttle limits.
=> Add pot shuffle and API throttling whitelist

app/Http/Controllers/CustomizerController.php, app/Http/Controllers/RandomizerController.php, app/Http/Requests/CreateRandomizedGame.php, app/Rules/OverrideStartScreenRule.php, app/World.php, package-lock.json, routes/console.php
This PR will allow an API request to override the start screen code.  The primary use case for this is the ALTTPR Ladder, as they need a way to ensure that all ladder seeds in a given race have the same code.
=> Allow override of Start Screen Code

app/Enemizer.php, app/World.php, composer.json, composer.lock
This PR is intended to be used with this version of Enemizer: https://github.com/tcprescott/Enimizer/releases/tag/2mb-rom
This does four things:
1) Relocates Enemizer to bank 36, which is currently unused.
2) Sets enemized games to have a 2MB ROM.
3) Comments out the code that changes Aghanim, as it was causing strange behavior during Aghanim 2.  Also comments out sprite on hit.  We're not using either of these features on alttpr.com.
4) Removes the watermark on the character select screen.
These changes are primarily focused on masking the usage of Enemizer when playing mystery.
Thanks Zarby89 for providing the required changes.
=> Switch Enemizer to a 2MB ROM

resources/js/app.js, resources/js/components/VTRomSettings.vue, resources/js/components/VTSpriteLoader.vue, resources/js/components/VTSpriteSelect.vue, resources/js/store/customizer.js, resources/js/views/Customizer.vue, resources/js/views/HashLoader.vue, resources/js/views/Randomizer.vue, resources/js/vue-i18n-locales.generated.js, resources/lang/de/rom.php, resources/lang/en/rom.php, resources/lang/es/rom.php, resources/lang/fr/rom.php
TODO:
- Localization of error messages
- Remembering user preference? (EDIT: Done)
- Add icon-custom gfx (currently shares icon-custom-Random)
- Improve button/text alignment in VTSpriteLoader.vue
Testing performed:
- Verified loading several valid .zspr files works, and correctly
patches the ROM
- Verified select interface only appears when Load Custom Sprite
is selected, and otherwise does not change the normal GUI
- Verified loading a bogus .zspr file displays an error message
=> Add Load Custom Sprite entry to VTRomSettings/VTSpriteLoader

app/Console/Commands/UpdateBuildRecord.php, app/Rom.php
This patch instead uses the `git log` command to get the date of the latest commit, and use that instead of just using the current date.  This will result in a more consistent experience when using `php artisan alttp:updatebuildrecord`.
=> Get the last commit from the ROM repo and use that

app/Rom.php, app/World.php, config/sprites.php, resources/sass/_sprites.scss, resources/views/updates.blade.php
- Updates sprite list based on what was provided by Fish
- Mystery games now have the intro text "masked", making it harder to identify if a game is inverted, or entrance randomizer.
- Updates patch notes (notes assume that https://github.com/sporchia/alttp_vt_randomizer/pull/890 will be merged)
This PR also relies on assets being uploaded to S3.
=> V31.0.7 - Sprite and patch notes updates, also intro mystery masking

app/Boss.php, app/Region/Inverted/DarkWorld/DeathMountain/West.php, app/Region/Inverted/DarkWorld/NorthEast.php, app/Region/Inverted/DarkWorld/South.php, app/Region/Inverted/DesertPalace.php, app/Region/Inverted/EasternPalace.php, app/Region/Inverted/GanonsTower.php, app/Region/Inverted/HyruleCastleEscape.php, app/Region/Inverted/LightWorld/NorthEast.php, app/Region/Inverted/LightWorld/NorthWest.php, app/Region/Inverted/LightWorld/South.php, app/Region/Inverted/SwampPalace.php, app/Region/Inverted/TowerOfHera.php, app/Region/Standard/DarkWorld/DeathMountain/West.php, app/Region/Standard/DarkWorld/Mire.php, app/Region/Standard/DarkWorld/NorthEast.php, app/Region/Standard/DarkWorld/NorthWest.php, app/Region/Standard/DarkWorld/South.php, app/Region/Standard/IcePalace.php, app/Region/Standard/LightWorld/NorthWest.php, app/Region/Standard/PalaceOfDarkness.php, app/Region/Standard/SkullWoods.php, app/Support/ItemCollection.php, app/World.php, tests/Support/ItemCollectionTest.php
This PR adjusts the two methods to take the difficulty setting into account as per #826 
- canExtendMagic will now apply a modifier of 0.5 and 0.25 for hard and expert mode respectively.  These values are guesses on my part so they might require adjustment.
- canBunnyRevive will now return false if the difficulty setting is hard or expert.
=> Adjust canExtendMagic and canBunnyRevive

app/Randomizer.php
Refactors the priority of the silvers hint so it's more what we'd expect.  I merged the handling of standalone silver arrow upgrade with the progressive bow, into a simple if/else statement.
First it checks if there are at least two progressive bows, and that the bow limit is at least 2.  If so, do the normal thing with the progressive bows.
If not, then it checks if there's a silver arrow upgrade, or a bow and silver arrows item, if so, then write the hint.
If neither scenario applies, that means silvers aren't available.  Roll a fake hint and write it.
=> Refactor Silvers Hint

app/Console/Commands/Randomize.php
- **For next release**
- Accepts case-insensitive `true` to activate quickswap
- **QUESTION**: For CLI, do we have to ensure that quickswap is allowed? I noted the JS side checks for Tournament mode or a simple `allowQuickswap` variable
- This implementation will allow quickswap regardless, in its current state.
- **ANSWER** (from Synack): Don't worry about it
=> Added --quickswap CLI Option

resources/js/components/Customizer/EquipmentSelect.vue
- Would only save if you dragged, but clicking to select a new starting hearts value wouldn't trigger `saveEquipment()`
- Now capturing this via `@Click.native`
- `@Click` doesn't work, so using `@Click.native`
- [Relevant thread](https://github.com/NightCatSama/vue-slider-component/issues/175)
=> Customizer: Save Starting Hearts on Click

app/Randomizer.php, app/Rom.php, app/Services/HintService.php, app/Support/ItemCollection.php, app/World.php, composer.json, composer.lock, config/alttp.php, tests/RomTest.php, tests/Support/ItemCollectionTest.php
This gives us more flexibility to only make specific changes that are provided by the item functionality setting.  We get rid of rom.HardMode and instead break it into individual flags that are wrapped up into item.functionality
Additionally, it lets us set the amount the escape checkpoints refill a resource for, based on uncle weapon.
Finally, it switches the hard item shop changes to be based on Item Pool setting, not Item Functionality.  This is also a separate flag that we can then set at will.
=> Split rom.HardMode into separate config flags on World

app/Randomizer.php, app/Region.php, app/World.php
Fix uncle bomb fill for standard no logic (should only apply to customizer with a non-weapon manually placed on uncle).
Make escape key wild for standard no logic.
=> Remove logic from no logic Raindo

app/Randomizer.php
Determine which shop shields are available via the shield overflow count.
Replace fire shield in dark world forest shop with a green twenty for expert+ item pool.
Replace shields in regular dark world shops with a green twenty for super expert and crowd control.
=> Hard item pool shops.

app/Rom.php
Sets the "secrets" data for these tiles to be nothing so they dig like a regular grass tile. Addresses via kan.
=> Remove diggable light world portals in inverted

app/World.php
This leaves the Aga tower door unlocked during rain state in glitched modes, otherwise preserves vanilla behavior. If the mode is inverted, setInvertedMode sets this byte separately.
=> Unlock Aga Tower door during standard escape in glitched modes

app/Region/Inverted/DarkWorld/NorthEast.php, tests/Inverted/DarkWorld/NorthEastTest.php
Allow Mirroring to Catfish when you can get to Light World Zora Area.
This can happen via a Pre Activated Flute / Fake Flute to Death Mountain for Aga Light World Access
Also changed Unit Tests to reflect new Catfish Access.
Bug Reported and Change Requested by StructuralMike#5345 on [Discord](https://discord.com/channels/307860211333595146/307860548878336001/967368142995193856)
=> Mirror to Inverted Catfish

app/Region/Standard/MiseryMire.php
Fixes a small inconsistency where the big key can be in one of the two left side Mire chests but is considered unreachable without 3 keys, preventing some safe item configurations from being possible.  This brings the php randomizer to parity with ER in this regard.
=> Allow access to left side Mire with 2 keys if big key is there

app/Region/Inverted/LightWorld/NorthEast.php, tests/Inverted/LightWorldTest.php, tests/InvertedMajorGlitches/LightWorldTest.php, tests/InvertedOverworldGlitches/LightWorldTest.php, tests/MajorGlitches/DarkWorld/NorthEastTest.php, tests/NoGlitches/DarkWorld/NorthEastTest.php, tests/OverworldGlitches/DarkWorld/NorthEastTest.php
Add missing brackets around magic extension logic.
Adjust magic extension logic in swordless to be in line with the tempered version of that logic.
Add Tests for Standard + Inverted Ganon being unbeatable without firesource or swords.
=> Fix Inverted Ganon Firerod/Lamp Logic

app/Filler/RandomAssumed.php, app/Http/Controllers/CustomizerController.php, app/Randomizer.php, app/Region/Standard/DarkWorld/NorthEast.php, app/Rom.php, app/World.php, config/alttp.php, resources/js/store/modules/randomizer.js, resources/lang/de/options.php, resources/lang/de/randomizer.php, resources/lang/en/options.php, resources/lang/en/randomizer.php, resources/lang/es/options.php, resources/lang/es/randomizer.php, resources/lang/fr/options.php, resources/lang/fr/randomizer.php, resources/views/updates.blade.php, tests/RomTest.php
Adds a new goal called "Ganonhunt".  There are some things that I think we may still need to do regarding this PR, but I wanted to give you at least a first look at it.  This will not currently work with Entrance Randomizer, and as a result it has been explicitly disabled.  The frontend will force entrance shuffle off if the new goal is chosen, and if entrances are turned on while the new goal is chosen, it'll set the goal to Fast Ganon.
Rules:
1. Pyramid is pre-opened.
2. Agahnim 2 is not required
3. Crystals are not required to defeat Ganon.  Ganon vulnerability is strictly 40 Triforce Pieces.
4. Crystals are still required for GT entry.  GT fill rules are the same as the other Ganon goals.
Remaining (potential) tasks:
=> New Ganonhunt goal

config/alttp.php
This replaces the preset to make it default to 100% locations (AKA the crosskeys2023 preset). This has been the overwhelming majority in racing since it has been introduced and is the mode of the Crosskeys tournament as well.
I chose to not touch hints here, even though most racers run without hints. I think it may be worth revisiting that.
=> Modifies crosskeys preset to default to 100% Locations accessibliity
